name: Release HW

on:
  push:
    tags:
      - 'hw-v*'
      - 'sensado-soldadoras-hw-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
